int AddMegaScriptBytes(byte*, uint64*, int, uint64*, byte**);
int AddObjectClassToEnvironment(ScriptEnvironment*, Symbol*, uint64, byte*, uint32, byte, void*);
uint64 AllocateScriptMemory(ScriptEnvironment*, Script*, uint64);
int AssignData(ScriptEnvironment*, Script*, StackData, StackData);
float CastToFloat32(StackData);
double CastToFloat64(StackData);
float128 CastToFloat128(StackData);
uint64 CastToUnsignedInt64(StackData);
byte CompareSymbolStrings(byte*, byte*, short);
TemporarySymbol ConvertSymbolToDebris(Symbol);
Symbol CreateBasicDataTypeSymbol(ScriptEnvironment*, Script*, byte*, byte, void*);
int64 CreateLabel(ScriptEnvironment*, Script*, Symbol);
int64 CreateSymbol(ScriptEnvironment*, Script*, Symbol);
Symbol CreateStructElementSymbol(ScriptEnvironment*, Script*, byte*, byte, byte*);
Symbol CreateStructTypedefSymbol(ScriptEnvironment*, Script*, byte*, Symbol*, uint64);
int CreateVariableTemplate(ScriptEnvironment*, Script*, uint64*, byte, Symbol*, short);
int DestroyObject(ScriptEnvironment*, Object*);
int EnableMegaScript(ScriptEnvironment*, Script*);
int ExecuteMegaScriptOperation(ScriptEnvironment*, Script*, uint32);
void ExecuteStandardWarnCallbacks(ScriptEnvironment*, Script*, byte*);
StackData ExpandDebris(ScriptEnvironment*, Script*, StackData);
StackData ExpandDebrisDelete(ScriptEnvironment*, Script*, StackData);
StackData ExpandDebris(ScriptEnvironment*, Script*, StackData);
StackData ExpandStackData(ScriptEnvironment*, Script*, StackData);
StackData ExpandStackDataNoDelete(ScriptEnvironment*, Script*, StackData);
StackData ExpandStackSymbol(ScriptEnvironment*, Script*, StackData);
int64 FindLabel(ScriptEnvironment*, Script*, byte*, byte);
ObjectClassInformation *FindObjectClass(ScriptEnvironment*, uint64);
int64 FindScriptByName(ScriptEnvironment*, byte*);
int64 FindSymbol(ScriptEnvironment*, Script*, byte*, byte);
int64 FindTypedef(ScriptEnvironment*, Script*, byte*, byte);
int FreeScriptMemory(ScriptEnvironment*, Script*, uint64);
void ftoa(float, char*, int);
StackData FullyExpandStackData(ScriptEnvironment*, Script*, StackData);
int GetDataTypeLength(byte);
int GetDataTypeSize(byte);
TemporarySymbol GetDebrisFromStackData(Script*, StackData);
TemporarySymbol GetDebrisFromStackDataOptions(Script*, StackData, int);
char *GetFileString(byte*);
ObjectClassInformation *GetObjectClassInformation(ScriptEnvironment*, int);
ObjectClassInformation *GetObjectClassInformationByName(ScriptEnvironment*, char*);
uint64 GetPointerFromStackData(StackData);
uint64 GetPointerStackData(StackData);
int64 GetRecursiveStructSize(ScriptEnvironment*, Script*, uint64);
Symbol *GetSymbolFromStackData(Script*, StackData);
extern int InitializeEnvironment(ScriptEnvironment*);
extern int ExecuteMasterCycle(ScriptEnvironment*);
int InheritSymbolsFromMaster(ScriptEnvironment*, Script*);
int InitializeLibrary(ScriptEnvironment*, Script*);
StackData PopScriptStackData(Script*);
char *PopScriptStackString(ScriptEnvironment*, Script*);
int PushScriptStackData(Script*, byte*, byte);
int PrintCallDataHandler(ScriptEnvironment*, Script*, StackData, byte);
void *ReadScriptMemoryRange(ScriptEnvironment*, Script*, uint64, uint64);
int StandardLoadCall(ScriptEnvironment*, Script*, byte);
int WriteScriptMemory(ScriptEnvironment*, Script*, uint64, byte);
int WriteScriptMemoryRange(ScriptEnvironment*, Script*, uint64, uint64, void*);
int ZeroScriptMemory(ScriptEnvironment*, Script*, uint64);